### ISSUE TITLE
[Card] 조회 기능 구현하기

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-planner#27]
## 🖊️ *Description*
카드 조회 기능 구현

## ✅ *Todo*
- [x]  카드 상태에 따른 카드 목록 조회
  - [x] 동적 쿼리 사용하기
- [x] 카드 ID / 타이틀에 따른 조회 기능 구현
- [x] 조회를 위한 인자값을 받을 때 request에서 유효성 검사
- [x] 로직 내에서 예외처리 구현
- [x] repository에서 나온 Card 객체들을 response에 담아 반환
- [x] Service 테스트 코드 작성
  - [x] 커버리지 80% 이상 

## 📗 *Etc*
Controller 테스트는 일괄로 진행 예정
