### ISSUE TITLE
[아키텍처] 클라이언트 단 DTO 와 내부 애플리케이션 로직(Service)와 의존성 끊도록 수정

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/wedding-planner#28]
## 🖊️ *Description*
request가 컨트롤러와 usecase에서도 사용되어 클라이언트(web)과 서비스 내부에 불필요한 의존성이 생김
따라서 request를 바로 usecase로 전달하지 않고 usecase를 위한 dto를 만들어 의존성 이슈 해결하기
## ✅ *Todo*
- [x] DTO 완전 맵핑 전략 스터디
- [x] command 키워드 활용해보기
- [x] 카드 생성 command 객체 구현 
- [x] 카드 수정 command 객체 구현 

## 📗 *Etc*
- 언젠간 고칠거 미리 빨리 고쳐서 유지보수 시간을 아끼자!
